// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by build.zig from the contents of dist/.
// To update, rebuild the web dashboard first.
const std = @import("std");

pub const Asset = struct {
    content: []const u8,
    mime_type: []const u8,
};

const asset_0 = @embedFile("dist/index.html");
const asset_1 = @embedFile("dist/vite.svg");
const asset_2 = @embedFile("dist/assets/index-Ct-xFt6d.css");
const asset_3 = @embedFile("dist/assets/index-C65BRLHh.js");
const asset_4 = @embedFile("dist/assets/index-C65BRLHh.js.map");

pub fn get(path: []const u8) ?Asset {
    const mem = @import("std").mem;
    const normalized = if (path.len > 0 and path[0] == '/') path[1..] else path;
    const lookup = if (normalized.len == 0) "index.html" else normalized;

    if (mem.eql(u8, lookup, "index.html")) {
        return .{ .content = asset_0, .mime_type = "text/html; charset=utf-8" };
    } else if (mem.eql(u8, lookup, "vite.svg")) {
        return .{ .content = asset_1, .mime_type = "image/svg+xml" };
    } else if (mem.eql(u8, lookup, "assets/index-Ct-xFt6d.css")) {
        return .{ .content = asset_2, .mime_type = "text/css; charset=utf-8" };
    } else if (mem.eql(u8, lookup, "assets/index-C65BRLHh.js")) {
        return .{ .content = asset_3, .mime_type = "application/javascript; charset=utf-8" };
    } else if (mem.eql(u8, lookup, "assets/index-C65BRLHh.js.map")) {
        return .{ .content = asset_4, .mime_type = "application/json" };
    } else {
        if (!mem.startsWith(u8, lookup, "api/")) {
            return .{ .content = asset_0, .mime_type = "text/html; charset=utf-8" };
        }
        return null;
    }
}
